### PR TITLE
TODO App Features | Projects and Tasks

### PR DESCRIPTION
**Pull request by pointerish**
This PR implements the following:

- TODO App
- Tasks managed by project
- JS Navigation using ES6 modules compiled by Webpack

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
#### Changes Required! :recycle:
Hi team! I like your UI, it is really simple and easy to figure out! :+1:  It is also impressive how you leveraged bootstrap to pull off your design with minimum custom css! :ok_hand: However, there are some requirements I think you missed while implementing the project. These include:
- [ ] Make use of localStorage to save todos between sessions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/localstorage_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] A user should be able to edit the details of a to-do item. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] A user should also be able to delete a to-do. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
- [ ] A task should have a: ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/todo_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
  * title
  * description
  * due date
  * priority 

* [x] Add the necessary common commands like `build`, `development` in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))

```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
* [ ] __[Optional]__ Make your `README.md` file more descriptive. e.g:
  * it's about section references the library app,
  * the `live link` is broken, and
  * instructions for locally running your application stop at cloning your repository

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @pointerish and @NataJenkins  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
:+1: Frankly, your UI is awesome, I personally liked your innovation about UI/UX
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] I was not able to test your project on my local machine because after installing all of the necessary tools to run it, I couldn't create any project due to the error below on the screenshot:
Screenshot from 2021-05-03 23-04-27

Hence, I relied on the live demo link on your readme file, and sorry that I am not approving your project because it appears to me that the following requested changes are not yet addressed successfully:
   - [ ] Make use of localStorage to save todos between sessions
   - [ ] A user should be able to edit the details of a to-do item. 
   - [ ] A user should also be able to delete a to-do.
  - title :heavy_check_mark: 
  - description :x:
  - due date :x:
  - priority :x: 

:x: means that requirement is missing
:heavy_check_mark: means that requirement is present

Kindly, address all of the requested changes!!!

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Good job on using local storage :+1: 

To improve :factory_worker: [REQUIRED]:

- [x]  Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history. (eg: // taskInput.setAttribute("value", `${title}`); isCompleted?)
- [x] Kindly add .vscode into the .gitignore file and ensure that it is not uploaded to GitHub repo since it is not a project file.

- [x] It will be nice if you add necessary run common command like `development` in your `package.json` inside `scripts`. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
`"dev": "webpack --mode development",`

- [x]  Do not use `console.log`, `console.error`, ... . It's ugly, it kills performance. and it can make confidential data be visible in the browser tools. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/console_log_requirement.png) from Pathwright)
- [x] Please, make sure that you use this [.github/workflows/linters.yml](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml) file in your project.
- [x] Make sure that your `To-do item` has `priority` info

Nice to have:

- [x] Your live demo link is broken
- [ ] Add `webpack-dev-server` in your` devDependencies`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))
- [ ] It will be nice if you add instructions about how to run your APP in the readme file.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @pointerish and @NataJenkins  , your project is approved :tada: :tada: :tada: 
You have implemented almost everything critical for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,
### Just to make sure that everything is covered, you need to do the following before merging to the base branch:
- [ ] I can see that you have added `.vscode` in your .gitignore file, but it is still in your project, to remove it run `git rm -rf .vscode` and then commit the changes, after pushing that commit then you will be ready to go

Don't forget to fill the mandatory project completion form, and see you to next project,

## Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
